[build]
  publish = "docs"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/agrivoltaics"
  to = "/agrivoltaics/"
  status = 301

[[redirects]]
  from = "/agrivoltaics/*"
  to = "/agrivoltaics/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
for = "/docs/fonts/vazirmatn/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/*.woff2"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
