[build]
  publish = "docs"
  command = "npx tailwindcss -i docs/assets/tailwind.input.css -o docs/assets/tailwind.css --minify"
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
for = "/docs/fonts/vazirmatn/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/*.woff2"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
for = "/.netlify/functions/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://wesh360.ir"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type"
