[build]
  publish = "docs"
  command = "npx tailwindcss -i docs/assets/tailwind.input.css -o docs/assets/tailwind.css --minify"
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

