[build]
command = "npm ci && node scripts/build-cld.js"
publish = "docs"
[build.environment]
NODE_VERSION = "18"
CI = "true"
[build.processing]
skip_processing = true
[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
