name: CLD Checks
on:
  pull_request:
  push:
    branches: [work]
jobs:
  cld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run check:cld-html
      - run: npm run build
